grid_map_topic: /control/mapmanager/globalmapviz
grid_map_visualizations:
  - name: slope
    type: occupancy_grid
    params:
     layer: slope
     data_min: 0.0
     data_max: 90.0
  - name: satDriveability
    type: occupancy_grid
    params:
     layer: satDriveability
     data_min: 0.0
     data_max: 2.0
  - name: satDriveabilityConf
    type: occupancy_grid
    params:
     layer: satDriveabilityConf
     data_min: 0.0
     data_max: 1.0
  - name: satObjectHeight
    type: occupancy_grid
    params:
     layer: satObjectHeight
     data_min: 0.0
     data_max: 100.0
  - name: keyframeDriveability
    type: occupancy_grid
    params:
     layer: keyframeDriveability
     data_min: 0.0
     data_max: 2.0
  - name: keyframeDriveabilityConf
    type: occupancy_grid
    params:
     layer: keyframeDriveabilityConf
     data_min: 0.0
     data_max: 1.0
  - name: keyframeObjectHeight
    type: occupancy_grid
    params:
     layer: keyframeObjectHeight
     data_min: 0.0
     data_max: 100.0
  - name: reflectivity
    type: occupancy_grid
    params:
     layer: reflectivity
     data_min: 0.0
     data_max: 100.0
  - name: purpleProb
    type: occupancy_grid
    params:
     layer: purpleProb
     data_min: 0.0
     data_max: 1000.0
  - name: redProb
    type: occupancy_grid
    params:
     layer: redProb
     data_min: 0.0
     data_max: 1000.0
  - name: blueProb
    type: occupancy_grid
    params:
     layer: blueProb
     data_min: 0.0
     data_max: 1000.0
  - name: silverProb
    type: occupancy_grid
    params:
     layer: silverProb
     data_min: 0.0
     data_max: 1000.0
  - name: brassProb
    type: occupancy_grid
    params:
     layer: brassProb
     data_min: 0.0
     data_max: 1000.0

  - name: slopePC
    type: point_cloud
    params:
     layer: slope
  - name: satDriveabilityPC
    type: point_cloud
    params:
     layer: satDriveability
  - name: satDriveabilityConfPC
    type: point_cloud
    params:
     layer: satDriveabilityConf
  - name: satObjectHeightPC
    type: point_cloud
    params:
     layer: satObjectHeight
  - name: keyframeDriveabilityPC
    type: point_cloud
    params:
     layer: keyframeDriveability
  - name: keyframeDriveabilityConfPC
    type: point_cloud
    params:
     layer: keyframeDriveabilityConf
  - name: keyframeObjectHeightPC
    type: point_cloud
    params:
     layer: keyframeObjectHeight
  - name: reflectivityPC
    type: point_cloud
    params:
     layer: reflectivity
  - name: purpleProbPC
    type: point_cloud
    params:
     layer: purpleProb
  - name: redProbPC
    type: point_cloud
    params:
     layer: redProb
  - name: blueProbPC
    type: point_cloud
    params:
     layer: blueProb
  - name: silverProbPC
    type: point_cloud
    params:
     layer: silverProb
  - name: brassProbPC
    type: point_cloud
    params:
     layer: brassProb
