grid_map_topic: /control/safepathing/mapviz
grid_map_visualizations:
  - name: resistance
    type: occupancy_grid
    params:
     layer: resistance
     data_min: 0.0
     data_max: 5.0
  - name: timeOfArrival
    type: occupancy_grid
    params:
     layer: timeOfArrival
     data_min: 0.0
     data_max: 5.0
  - name: optimalPath
    type: occupancy_grid
    params:
     layer: optimalPath
     data_min: 0.0
     data_max: 10.0

  - name: resistancePC
    type: point_cloud
    params:
     layer: resistance
  - name: timeOfArrivalPC
    type: point_cloud
    params:
     layer: timeOfArrival
  - name: optimalPathPC
    type: point_cloud
    params:
     layer: optimalPath
